### ISSUE TITLE
[css] box-shadow

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#120]
```css
.box {
				height: 150px;
				width: 300px;
				margin: 20px;
				border: 1px solid #ccc;
			}
			
			.top {
				box-shadow: 0 -5px 5px -5px #333;
			}
			
			.right {
				box-shadow: 5px 0 5px -5px #333;
			}
			
			.bottom {
				box-shadow: 0 5px 5px -5px #333;
			}
			
			.left {
				box-shadow: -5px 0 5px -5px #333;
			}
			
			.all {
				box-shadow: 0 0 5px #333;
			}
```
