### ISSUE TITLE
[css] square div 

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#123]
```css
.div {
 padding-bottom: 20%;
 width: 20%;
 height: 0;
 background-color: red;
}
```
