### ISSUE TITLE
[css] mask-image

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#127]
```html
<div id="masked"></div>
```

```css
#masked {
  width: 100px;
  height: 100px;
  background-color: #8cffa0;
  -webkit-mask-image: url(https://mdn.mozillademos.org/files/12676/star.svg);
  mask-image: url(https://mdn.mozillademos.org/files/12676/star.svg);
  transition: all, .3s;
  &:hover {
    transform: scale(.5);
  }
  &:active {
    animation: animate 1s linear both infinite;
  }
}

@keyframes animate {
  0% {
    background-color: #8cffa0;
  }
  50% {
    background-color: #000000;
  }
  100% {
    background-color: #8cffa0;
  }
}
```
