### ISSUE TITLE
[css] linear-gradient

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#130]
```html
<div class="box"></div>
```
```css
.box {
  width: 100px;
  height: 100px;
  
  background: linear-gradient(
  to right, 
  transparent,
  red 70%);
  background-size: 200% 100%;
}
```
