### ISSUE TITLE
[js] get element total height

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#131]
```html
<div class="box">123</div>
<div class="result"></div>
```

```js
function getElementTotalHeight({ele} = {}) {
  let element = ele
	  	height = element.getBoundingClientRect().height,
    	style = window.getComputedStyle(element);

  		height = ['top', 'bottom'].map(side => {
      	return parseInt(style['margin-' + side], 10)
    	})
    	.reduce((total, side) => {
      	return total + side
	    }, height)
	
  		return height
}

const eleTotalHegiht = getElementTotalHeight({
  ele: document.body.querySelector('.box')
})

document.body.querySelector('.result').innerHTML = eleTotalHegiht
```

```css
.box {
  padding: 10px 0 20px;
  border-top: solid 2px red;
  border-bottom: solid 3px pink;
  margin: 5px 0 7px;
  background-color: yellow;
}
```
