### ISSUE TITLE
[css] fix blurry Image on transform scale

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#133]
```css
img {
 -webkit-backface-visibility: hidden;
 -ms-transform: translateZ(0);
 -webkit-transform: translateZ(0);
 transform: translateZ(0);
}
```
