### ISSUE TITLE
[css] Vertical padding is relative to element’s width not height

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#76]
> So padding-top: 50% does not add 50% of the original height of the element as padding, but 50% of the width of the parent element

```css
.square {
  width: 100%;
  height: 0;
  padding-bottom: 100%;
}
```
