### ISSUE TITLE
[小程式] 刮刮樂

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#78]
ps1. 亮點 `context.globalCompositeOperation = "destination-out"`
ps2. TODO: 手機版適用

[demo](https://jsfiddle.net/a8k15dm4/4/)

```html
<img src="https://images.unsplash.com/photo-1472152083436-a6eede6efad9?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a52890683599a39bd5b99b0487c642dc&auto=format&fit=crop&w=1349&q=80" alt="">
<canvas id="canvas" width="400" height="300"></canvas>
```
```js
var canvas = document.getElementById("canvas");
var context = canvas.getContext('2d');

//画蒙布
context.beginPath();
context.fillStyle = 'grey'
context.fillRect(0, 0, 400, 300);

//鼠标按下开刮
canvas.onmousedown = function() {
  canvas.onmousemove = function() {
    //获取鼠标坐标
    var x = event.clientX;
    var y = event.clientY;
    //destination-out           显示原来的不在后来区域的部分
    context.globalCompositeOperation = "destination-out";
    context.beginPath();
    context.arc(x - 200, y, 30, 0, Math.PI * 2);
    context.fill();
  }
}
//鼠标抬起不刮开
canvas.onmouseup = function() {
  canvas.onmousemove = function() {}
}
```
```css
* {
  margin: 0;
  padding: 0;
}

img {
  width: 400px;
  height: 300px;
  left: 200px;
  position: absolute;
  z-index: -1;
}

canvas {
  margin-left: 200px;
}
```
