### ISSUE TITLE
[scss] triangle

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#8]
```scss
// 三角形基本樣式
%basic-triangle-type {
	content: '';
	position: absolute;
	width: 0px;
	height: 0px;
	border-style: solid;
	z-index: 10;	
}

// 三角形基本樣式 (上下左右)
@mixin triangle-up($color,$top,$left,$width,$height) {
	@extend %basic-triangle-type; 
	top: $top;
	left: $left;
	border-width: 0 $width $height $width;
	border-color: transparent transparent $color transparent;	
}

@mixin triangle-down($color,$top,$left,$width,$height) {
	@extend %basic-triangle-type; 
	top: $top;
	left: $left;
	border-width: $height $width 0 $width;
	border-color: $color transparent transparent transparent;
}

@mixin triangle-right($color,$top,$left,$width,$height) {
	@extend %basic-triangle-type; 
	top: $top;
	left: $left;
	border-width: $width 0 $width $height;
	border-color: transparent transparent transparent $color; 	
}

@mixin triangle-lef($color,$top,$left,$width,$height) {
	@extend %basic-triangle-type; 
	top: $top;
	left: $left;
	border-width: $width $height $width 0;
	border-color: transparent $color transparent transparent;	
}
```
