### ISSUE TITLE
[css] font setting

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#82]
```css
[lang^="zh"] body {
font-family: "Hiragino Sans GB","华文细黑","STHeiti","微软雅黑","Microsoft YaHei",SimHei,"Helvetica Neue",Helvetica,Arial,sans-serif;
}

```
