### ISSUE TITLE
[css] vmin - vmax

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/-WORK_TIP#92]
[demo](https://jsfiddle.net/fsosa7mL/) 

```css
/* 
vmin : 長或寬較小的那個的百分比
vmax : 長或寬較大的那個的百分比
*/

$square: 10vh;
$fontSize: 4vmin;
$value: $fontSize / 2;
.header {
  padding: 10vmin;
  background-color: #4a4a4a;
  font-size: 4vmin;
}

.header .items {
  margin: 5px;
  width: $square;
  height: $square;
  line-height: calc($square - $value);
  text-align: center;
  background-color: #fff;
}

```
